### ISSUE TITLE
build_image.sh failed

### ISSUE THREAD

**Issue by echowhisky** [nbgallery/jupyter-docker#1]
I pulled a copy of commit a2a83a7 and ran: 
`./build_image.sh jupytergallery/base:latest`

It failed during Step 13:

> /usr/local/bin/min-apk: line 5: strip: not found
> /bin/sh: min-package: not found
> The command '/bin/sh -c min-apk     bash     bzip2     curl     file     gcc     g++     make     openssh-client     patch     readline-dev     tar     tini &&   min-package http://download.zeromq.org/zeromq-4.0.4.tar.gz &&   rm /usr/local/share/man/_/zmq_ &&   rm -rf /usr/include/c++/_/java &&   rm -rf /usr/include/c++/_/javax &&   rm -rf /usr/include/c++/_/gnu/awt &&   rm -rf /usr/include/c++/_/gnu/classpath &&   rm -rf /usr/include/c++/_/gnu/gcj &&   rm -rf /usr/include/c++/_/gnu/java &&   rm -rf /usr/include/c++/_/gnu/javax &&   rm /usr/libexec/gcc/x86_64-alpine-linux-musl/_/cc1obj &&   rm /usr/bin/gcov\* &&   rm /usr/bin/gprof &&   rm /usr/bin/*gcj' returned a non-zero code: 127

**Comment by jeffyjefflabs** [comment]
I can't reproduce.  Strip should be installed with binutils as one of the dependencies -- I get 34 total apks installed by that step.  The min-package script should be installed into /usr/local/bin by the COPY command a few steps earlier.

**Comment by kylekyle** [comment]
Either way, we should remove `build_image.sh` entirely and just rely on the base image with dynamic kernels. I'll close this ticket when that's done.

**Comment by kylekyle** [comment]
build_image.sh is no more. We have an ask repo with kernels that are installed when needed.
