### ISSUE TITLE
jupyter interrupt doesn't work after loading iruby dependencies

### ISSUE THREAD

**Issue by sethfarns** [nbgallery/jupyter-docker#12]
After I load my dependencies (doesn't matter which gems are loaded), the 'interrupt kernel' command in Jupyter no longer functions. It still gives the 'interrupting kernel' notification, but it doesn't actually interrupt anything. @kylekyle

**Comment by kylekyle** [comment]
Okay, this should be filed against iruby-dependencies. 

Earlier this year the bundler team released 1.14.0 which broke iruby-dependencies. I suspect that bundler is exec'ing something in a way that confuses zmq (see [ipython issue #3400](https://github.com/ipython/ipython/issues/3400)).  

Right now you can fix this by installing the previous version of bundler from the terminal in jupyter:

```bash
# gem uninstall bundler
# gem install bundler -v 1.13.7
```

I'll figure out exactly what is happening and release a new version of iruby-dependencies. I should also note that in bundler 1.13.7 interrupting a sleep works, but doesn't produce an Interrupt error message which is weird.

**Comment by fenwanderer** [comment]
I'm guessing @kylekyle temporarily fixed this with nbgallery/iruby-dependencies@d125ebea440d03539663bb65f0cd4173aa561d25 back on Apr 27.

Converted this into nbgallery/iruby-dependencies#2; closing this one.
