### ISSUE TITLE
How to use insecure (no auth) Jupyter notebook server when using in another Dockerfile?

### ISSUE THREAD

**Issue by jamesmcm** [nbgallery/jupyter-docker#15]
Hi,

I want to use this as part of another Dockerfile but I need to use the standard Jupyter notebook without authentication and without HTTPS.

Is there an easy way of doing this, aside from forking the whole repo for such a small change?

**Comment by jamesmcm** [comment]
I fixed this adding the following lines to my Dockerfile:


```
FROM nbgallery/jupyter-alpine

RUN printf "c.NotebookApp.token = ''\n" >> /root/.jupyter/jupyter_notebook_config.py
RUN printf "c.NotebookApp.password = ''\n" >> /root/.jupyter/jupyter_notebook_config.py

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["jupyter-notebook", "--allow-root"]
```

**Comment by jeffyjefflabs** [comment]
You can also set the token and password to blank on the command line, so this should work too:

```
CMD ["jupyter-notebook", "--allow-root", "--JupyterApp.token=''", "--JupyterApp.password=''"]
```

Also, in version 7 of the image, we have an alternate entrypoint called `jupyter-notebook-insecure-for-testing-only` that wraps all that up.  As you can tell by the name, we only use it for testing, but you could change your CMD to use it.  ~~It's in the v7 branch (which I apparently forgot to merge back to master)~~:

https://github.com/nbgallery/jupyter-docker/blob/master/util/jupyter-notebook-insecure-for-testing-only
