### ISSUE TITLE
"Run in Jupyter" in nbgallery is not working

### ISSUE THREAD

**Issue by ejunial** [nbgallery/jupyter-docker#23]
When trying to run a notebook in jupyter from my nbgallery App, i get an error:
Run failed
Could not send notebook to https://172.17.0.4:443/.

The Jupyter server is running and i can run the notebook directly using https://172.17.0.4:443 in my browser . But when trying to do the same from nbgallery it does not work. (The "Jupyter Enviroment" is set to that same address)

Any clues or hints that could point me in the right direction would be much appreciated

B r
/Junior

**Comment by jeffyjefflabs** [comment]
Sorry, I overlooked this issue.  Were you able to get it working?  My first suggestion would be to make sure that both nbgallery and Jupyter are running secure https (or both insecure http) - the web browser won't allow mixed content.  Also [check your Jupyter configuration settings](https://github.com/nbgallery/nbgallery/blob/master/docs/jupyter_integration.md#manual-configuration).

**Comment by jeffyjefflabs** [comment]
Oh, right, you opened an [issue in the nbgallery repo](https://github.com/nbgallery/nbgallery/issues/48) too.  I'm going to close this one as a duplicate.

**Comment by ejunial** [comment]
No problema, thanks anyway...:-)
