### ISSUE TITLE
Update Ruby display name to reflect actual version

### ISSUE THREAD

**Issue by fenwanderer** [nbgallery/jupyter-docker#8]
Display shows Ruby 2.2.4, but the actual installed version is 2.3.1p112.  Needs to be changed in kernels/ruby/kernel.json.

Is there a way to determine this dynamically?  Or is it better to leave off the version number completely?

**Comment by kylekyle** [comment]
You're running an out-of-date image.

**Comment by fenwanderer** [comment]
Really?  I cloned this repo and built the image from master the day I filed the ticket.  And [jupyter-docker/kernels/ruby/kernel.json](https://github.com/jupyter-gallery/jupyter-docker/blob/master/kernels/ruby/kernel.json) still has Ruby 2.2.4 hard-coded, while running `ruby --version` in the Jupyter terminal gave me 2.3.1p112.  What am I missing?

**Comment by kylekyle** [comment]
Whoops! Never pushed my commit. Teach me not to be dismissive.

**Comment by kylekyle** [comment]
Okay, it's fixed for realsy this time. It would be better to not have the version hard-coded, but it would take a bit of thought for how to do that. We could just list the language. That might make people crazy. Not sure. If you would like to do that, just open another ticket.
